version: '3.8'

services:
  app:
    image: my-wishlist  
    ports:
      - "8080:8080"  
    environment:
      APP_NAME: whitelist
      DB_URL: jdbc:mariadb://klbcedmmqp7w17ik.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/gnkt11raqcxa6jgn
      DB_USERNAME: jz3m5hiryit72qpk
      DB_PASSWORD: fpsro02vtut1o17g
      DB_DRIVER_CLASS: org.mariadb.jdbc.Driver
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: true
      JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
      HIKARI_MAX_POOL_SIZE: 10
      HIKARI_MIN_IDLE: 5
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password  
      MYSQL_DATABASE: gnkt11raqcxa6jgn          
      MYSQL_USER: jz3m5hiryit72qpk               
      MYSQL_PASSWORD: fpsro02vtut1o17g           
    ports:
      - "3306:3306"  

networks:
  default:
    driver: bridge